### ISSUE TITLE
Feature Request: Support File Action

### ISSUE THREAD

**Issue by IOIO72** [kawamataryo/alfred-imagemin#1]
This is a great tool! Would be even greater, if it would also appear in the file menu as well. :-)

**Comment by kawamataryo** [comment]
@IOIO72 

Thanks!!  That is good idea.
I will try to support the file menu as well.

**Comment by kawamataryo** [comment]
@IOIO72 
Supported File Action.
https://github.com/kawamataryo/alfred-imagemin/releases/tag/v1.4.0

**Comment by IOIO72** [comment]
> @IOIO72
> Supported File Action.
> https://github.com/kawamataryo/alfred-imagemin/releases/tag/v1.4.0

Very nice, great job! 🥇 
Thanks a lot! 👍
